### ISSUE TITLE
Fluentd rereading the whole log files

### ISSUE THREAD

**Issue by Charith32** [fluent/fluentd-docs-gitbook#89] opened 2019-07-25 01:25 UTC
I need to read a log file and separate its content based on a date it has(date is a PART of a field in a log line). I managed to separate the log files based on date. But the problem is that log lines are written to the same file causing log duplication. When I set append parameter to true, and add a new log line, It keeps adding logs to the same file. If I set it to false, multiple files will be created _0,_1 which aren't needed. I used pos_file parameter but it keeps reading from the beginning.
I made the read_from_head parameter to false but it still read from head of the file "WHEN I SAVE a new log line to the file".
Here is the configuration I used.

```
<source>
  @type tail
  format multiline
  format_firstline /TID:/
  format1 /(?<TenantID>TID: \[-1\].*)$/
  multiline_flush_interval 1s
  path /home/charith/Documents/fdConfig/wso2testlog.log
  pos_file /home/charith/Documents/fdConfig/fluentd_test1.pos
  tag test
  rotate_wait 5
  read_from_head false
  refresh_interval 60
</source>

<filter test>
  @type record_modifier
  #enable_ruby true
  #auto_typecast true
  <record>
    datefield ${record['TenantID'].scan(/(^(?!(TID: \\[-1\\]\\[\\] \[)))*(?<date>([0-9]{4})-([0-9]{1,2})-([0-9]{1,2}))/)}
  </record>
</filter>
<match test>
  @type file
  path /home/charith/Documents/fdConfig/TestEnv/${datefield}
  format single_value
  message_key TenantID
  <buffer datefield>
    @type memory
    flush_mode immediate
    ##flush_interval 3s
  </buffer>
  append true
</match>

```
Following are the example log line I used.
TID: [-1] [] [2019-07-14 20:68:38,334]  INFO {org.wso2.carbon.databridge.core.DataBridge} -  user admin connected {org.wso2.carbon.databridge.core.DataBridge}
TID: [-1] [] [2019-07-15 20:70:38,334]  INFO {org.wso2.carbon.databridge.core.DataBridge} -  user admin connected {org.wso2.carbon.databridge.core.DataBridge}
TID: [-1] [] [2019-07-15 20:71:38,334]  INFO {org.wso2.carbon.databridge.core.DataBridge} -  user admin connected {org.wso2.carbon.databridge.core.DataBridge}
TID: [-1] [] [2019-07-15 20:72:38,334]  INFO {org.wso2.carbon.databridge.core.DataBridge} -  user admin connected {org.wso2.carbon.databridge.core.DataBridge}
TID: [-1] [] [2019-07-15 20:73:38,334]  INFO {org.wso2.carbon.databridge.core.DataBridge} -  user admin connected {org.wso2.carbon.databridge.core.DataBridge}

**Comment by ganmacs** [comment] 2019-07-25 02:11
I tested in my local env. but I couldn't reproduce it.
Could you write a reproduction step more detail? 

BTW this repository is not for answering these kinds of questions.
Please use https://groups.google.com/forum/#!forum/fluentd.

I'm closing this issue. If you will write a reproduction step, could you create a new topic on fluentd's google groups and write it.

**Closed by ganmacs** 2019-07-25 02:11 UTC
