### ISSUE TITLE
Failure to resend secondary file through "fluent-cat command"

### ISSUE THREAD

**Issue by goslim56** [fluent/fluentd-docs-gitbook#306] opened 2021-04-23 02:14 UTC
I am sending data to kafka through fluentd config as below

I am accumulating logs of data that failed to be transmitted through secondary_file.

I followed the method you guided for retransmission, but only the phrase "Input must be a map (got Array)" is displayed.

Which part did I make a mistake?

====How i used flunetd-cat====
 cat /home/temp/eventqueue.log.0 | fluent-cat --format msgpack  --host 127.0.0.1 --port 24224 tag

=====my fluentd config======
![image](https://user-images.githubusercontent.com/12165782/115808500-8bbb8680-a425-11eb-847e-f620c981c4de.png)

**Comment by kenhys** [comment] 2021-04-28 02:28
Is `/home/temp/eventqueue.log.0` saved in msgpack format?
I guess that it may be saved as json format.

**Comment by goslim56** [comment] 2021-04-28 02:31
Is it possible to save secondary_file in json format?
I tried to save it in not msgpack format but json format, however couldn't find a way.
If you know how, please share it.

**Comment by kenhys** [comment] 2021-04-28 02:50
Thanks,
If the format of `/home/temp/eventqueue.log.0 ` is msgpack, it is expected.
so this failure may be caused by another reason.

**Comment by kenhys** [comment] 2021-04-28 03:01
This error is raised from


https://github.com/fluent/fluentd/blob/2cbb650b748c38602898af58c2d0eb251946a230/lib/fluent/command/cat.rb#L157

> raise ArgumentError, "Input must be a map (got #{record.class})"


so there is something weird with /home/temp/eventqueue.log.0 :thinking:

**Comment by goslim56** [comment] 2021-04-28 04:12
It is expected to be caused by requesting multiple messages in the form of an array in /home/temp/eventqueue.log.0 to "fluentd-cat" (because chunk_id is made by Kafka topic unit).

Is there a way to retransmit the secondary_file consisting of multiple messages rather than a single message?

**Comment by kenhys** [comment] 2021-04-28 07:46
Then, it may be better to use https://github.com/fluent/fluent-logger-ruby with Fluent::MessagePackFactory.

```ruby
require 'fluent-logger'
require 'fluent/msgpack_factory'

host = "localhost"
port = 24224
file = ARGV.first
File.open(file) do |f|
  begin
    u = Fluent::MessagePackFactory.msgpack_unpacker(f)
    u.each do |obj|
      time = obj.delete('time')
      logger = Fluent::Logger::FluentLogger.new(nil, :host => host, :port => port)
      logger.post_with_time('tag', obj, time)
    end
  rescue EOFError => e
  end
end
```

**Comment by goslim56** [comment] 2021-04-29 05:03
I used python's "msgpack.Unpacker" to retransmit after decoding.

Thanks for the kind explanation.

**Comment by kenhys** [comment] 2021-05-06 05:15
It may be useful if fluent-cat supports these files. :thinking:

**Comment by kenhys** [comment] 2021-05-13 02:18
It should be fixed by https://github.com/fluent/fluentd/pull/3368

**Comment by kenhys** [comment] 2021-05-17 06:01
https://github.com/fluent/fluentd/pull/3368 has been merged :+1:

**Closed by kenhys** 2021-05-17 06:01 UTC

**Comment by goslim56** [comment] 2021-05-17 23:41
Thank you so much for reflecting my opinion.
I'm really happy that I think I contributed to your source.
