### ISSUE TITLE
Multi-process workers and file buffer

### ISSUE THREAD

**Issue by msamoylov** [fluent/fluentd-docs-gitbook#252] opened 2020-11-17 10:35 UTC
The [documentation](https://docs.fluentd.org/deployment/multi-process-workers#root_dir-id-parameter) is outdated.

> With multi-process workers, you cannot use the fixed path configuration for file buffer because it conflicts buffer file path between processes.

With the given example you get `config error file="/fluentd/etc/fluent.conf" error_class=Fluent::ConfigError error="buffer path is not configured. specify 'path' in <buffer>"`

**Comment by repeatedly** [comment] 2020-11-17 10:52
Which point? I can't reproduce your error message.

```
% fluentd -c multi_file_buffer.conf
2020-11-17 19:48:40 +0900 [info]: parsing config file is succeeded path="multi_file_buffer.conf"
2020-11-17 19:48:40 +0900 [info]: gem 'fluent-plugin-prometheus' version '1.8.1'
2020-11-17 19:48:40 +0900 [info]: gem 'fluent-plugin-record-modifier' version '2.0.1'
2020-11-17 19:48:40 +0900 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '2.3.0'
2020-11-17 19:48:40 +0900 [info]: gem 'fluentd' version '1.11.4'
2020-11-17 19:48:40 +0900 [info]: [out_fwd] adding forwarding server 'localhost:24224' host="localhost" port=24224 weight=60 plugin_id="out_fwd"
2020-11-17 19:48:40 +0900 [info]: using configuration file: <ROOT>
  <system>
    workers 2
    root_dir "/tmp/fluentd"
  </system>
  <match pattern>
    @type forward
    @id out_fwd
    <service>
      host "localhost"
      port 24224
    </service>
    <buffer>
      @type "file"
    </buffer>
  </match>
</ROOT>
2020-11-17 19:48:40 +0900 [info]: starting fluentd-1.11.4 pid=94982 ruby="2.6.3"
2020-11-17 19:48:40 +0900 [info]: spawn command to main:  cmdline=["/path/to/ruby", "-Eascii-8bit:ascii-8bit", "/path/to/fluentd", "-c", "multi_file_buffer.conf", "--under-supervisor"]
2020-11-17 19:48:41 +0900 [info]: adding match pattern="pattern" type="forward"
2020-11-17 19:48:41 +0900 [info]: #0 [out_fwd] adding forwarding server 'localhost:24224' host="localhost" port=24224 weight=60 plugin_id="out_fwd"
2020-11-17 19:48:41 +0900 [info]: #1 [out_fwd] adding forwarding server 'localhost:24224' host="localhost" port=24224 weight=60 plugin_id="out_fwd"
2020-11-17 19:48:41 +0900 [info]: #0 starting fluentd worker pid=94997 ppid=94982 worker=0
2020-11-17 19:48:41 +0900 [info]: #1 starting fluentd worker pid=94998 ppid=94982 worker=1
2020-11-17 19:48:41 +0900 [info]: #0 fluentd worker is now running worker=0
2020-11-17 19:48:41 +0900 [info]: #1 fluentd worker is now running worker=1
```

**Comment by msamoylov** [comment] 2020-11-17 13:19
This configuration leads to the above-mentioned error message with fluentd 1.11.5, but uncommenting the `path` parameter fixes it. Any clues? 

```
<system>
      root_dir /var/log/fluentd
      workers 2
</system>

# Skipped

<match>
        @type copy
        @id internal_out

        <store>
          @type elasticsearch
          host "#{ENV['ES_HOST']}"
          port 9200
          scheme https
          user "#{ENV['ES_USER']}"
          password "#{ENV['ES_PASSWORD']}"
          logstash_format true
          logstash_prefix internal
          logstash_dateformat %Y%m%d
          include_tag_key true
          include_timestamp true
          time_key time
          type_name _doc
          reconnect_on_error true
          tag_key @log_name
          prefer_oj_serializer true
          reconnect_on_error true
          reload_on_failure true
          reload_connections false
          verify_es_version_at_startup false
          default_elasticsearch_version 7
          ssl_version TLSv1_2
          suppress_type_name true
          request_timeout 60s
          <buffer>
            @type file
            # path /var/log/fluentd/kubernetes.internal.system.buffer
            flush_mode interval
            retry_type exponential_backoff
            flush_thread_count 6
            flush_interval 5s
            retry_forever
            retry_max_interval 30
            retry_randomize true
            total_limit_size 5GB
            overflow_action "block"
          </buffer>
        </store>        
      </match>
    </label>
```

**Comment by repeatedly** [comment] 2020-11-18 22:00
You forgot to add `@id` to elasticsearch setting.

> root_dir/@id parameter
> These parameters must be specified when you use the file buffer.

**Comment by msamoylov** [comment] 2020-11-19 06:42
Are you saying I need `@id` in both `<match>` and `<store>` definitions?

**Comment by kenhys** [comment] 2021-03-19 05:14
FYI: https://docs.fluentd.org/deployment/multi-process-workers#root_dir-id-parameter will help.
If multiple `<store>` is used, add `@id` to `<store>`.

**Comment by kenhys** [comment] 2021-05-13 02:22
As https://github.com/fluent/fluentd-docs-gitbook/issues/252#issuecomment-729983574 resolves this issue, I'll close it.

**Closed by kenhys** 2021-05-13 02:22 UTC
